# Site settings
title: My Blog
header-img: img/home-bg.png
email: james.randolph2016@gmail.com
copyright_name: james-randolph-50
description: > # this means to ignore newlines until "baseurl:"
  Flatiron Fullstack Online Blog
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  james-randolph-50
learn_profile: james-randolph-50
email_username: james.randolph2016@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
